# Generated by Django 6.0.3 on 2026-03-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('platform', models.CharField(choices=[('AMAZON', 'Amazon'), ('MERCADOLIVRE', 'Mercado Livre'), ('CASASBAHIA', 'Casas Bahia'), ('MAGALU', 'Magalu')], db_column='plataforma', max_length=255, verbose_name='Plataforma')),
                ('url', models.URLField(db_column='url', max_length=255, verbose_name='URL')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('product', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='products.product', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Plataforma de Produto',
                'verbose_name_plural': 'Plataformas de Produtos',
                'db_table': 'tb_produto_plataforma',
            },
        ),
    ]
