# Generated by Django 6.0.3 on 2026-03-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productplatform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], db_column='canal', max_length=255, verbose_name='Canal')),
                ('min_price', models.DecimalField(db_column='preco_minimo', decimal_places=2, max_digits=10, verbose_name='Preço Mínimo')),
                ('max_price', models.DecimalField(db_column='preco_maximo', decimal_places=2, max_digits=10, verbose_name='Preço Máximo')),
                ('is_active', models.BooleanField(db_column='ativo', default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('product_platform', models.ForeignKey(db_column='id_produto_plataforma', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.productplatform', verbose_name='Plataforma de Produto')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Alerta de Preço',
                'verbose_name_plural': 'Alertas de Preço',
                'db_table': 'tb_alerta_preco',
            },
        ),
    ]
