# Generated by Django 6.0.3 on 2026-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productplatform',
            name='current_price',
            field=models.DecimalField(blank=True, db_column='preco_atual', decimal_places=2, max_digits=10, null=True, verbose_name='Preço Atual'),
        ),
        migrations.AddField(
            model_name='productplatform',
            name='last_checked_at',
            field=models.DateField(blank=True, db_column='ultima_verificacao', null=True, verbose_name='Última Verificação'),
        ),
    ]
