# Generated by Django 6.0.3 on 2026-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productplatform_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='last_checked_at',
            field=models.DateTimeField(db_column='data_verificacao', verbose_name='Data de Verificação'),
        ),
        migrations.AlterField(
            model_name='productplatform',
            name='last_checked_at',
            field=models.DateTimeField(db_column='ultima_verificacao', verbose_name='Última Verificação'),
        ),
    ]
